[package]
name = "django-fast-multipart-core"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Pravin", "Marcelo Trylesinski <marcelotryle@gmail.com>"]
description = "Internal Rust multipart parser for django-fast-multipart"
repository = "https://github.com/p-r-a-v-i-n/django-fast-multipart"
publish = false

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
memchr = "2.8.3"
pyo3 = { version = "0.29.2", features = ["abi3-py312", "extension-module"] }

[profile.release]
lto = true
codegen-units = 1
